version: "3"

services:
  frontend:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-dQng
    container_name: frontend
    restart: unless-stopped
    ports:
      - '8080:80' # Public HTTP Port
    volumes:
      - ./data/nginx/templates:/etc/nginx/templates
    networks:
      - dq-net
    environment:
      - NGINX_HOST=localhost

  cache:
    image: redis:7
    restart: always
    container_name: cache
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - dq-net
  backend:
    tty: true
    stdin_open: true
    restart: always
    environment:
      REDIS_HOST: "cache"
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - "./data/dq:/app/data"
    networks:
      - dq-net
    depends_on:
      - cache
    command: python main.py
  worker:
    tty: true
    stdin_open: true
    restart: unless-stopped
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile
    container_name: worker
    volumes:
      - "./data/dq:/app/data"
    networks:
      - dq-net
    depends_on:
      - cache
    command:
      - rq
      - worker
      - --url
      - redis://cache
networks:
  dq-net: