version: "3"

services:
  dq-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ./data/npm/data:/data
      - ./data/npm/letsencrypt:/etc/letsencrypt
    networks:
      - dq-net
  cache:
    image: redis:7
    restart: always
    ports:
    - '6379:6379'
    container_name: cache
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - dq-net
  backend:
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      REDIS_HOST: "redis://cache"
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - "./data/dq:/app/data"
    networks:
      - dq-net
    depends_on:
      - cache
    command: python main.py
  worker:
    tty: true
    stdin_open: true
    restart: unless-stopped
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile
    container_name: worker
    volumes:
      - "./data/dq:/app/data"
    networks:
      - dq-net
    depends_on:
      - cache
    command:
      - rq
      - worker
      - --url
      - redis://cache
networks:
  dq-net: